server.port: 8885
rabbitmq:
  username: guest
  password: guest
  host: localhost
  port: 5552
  stream:
    in: SensorMeasurement
#The Following end points used a k8 Readiness probbe
management:
  endpoints:
    web:
      exposure:
        include: info, health
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gemfire-stream-sink
gemfire:
  locators: localhost[10334]
  region:
    name: SensorMeasurement
    idFieldName: id
